obj-$(CONFIG_PROJECT_SMILE) += smile.o
obj-$(CONFIG_PROJECT_ARIEL) += ariel.o
obj-$(CONFIG_PROJECT_RAMSES) += ramses.o
obj-$(CONFIG_PROJECT_RAMSES) += ramses-uart0.o
obj-$(CONFIG_PROJECT_MYAPP) += myapp.o
