obj-y += sched/

obj-y += kmem.o
obj-y += ksym.o
obj-y += bitmap.o
obj-y += elf_loader.o
obj-y += module.o
obj-y += irq.o
obj-y += kthread.o
obj-y += time.o
obj-y += clockevent.o
obj-y += tick.o
obj-y += watchdog.o
obj-y += syscalls.o
obj-y += tty.o
obj-y += application.o
obj-y += edac.o
obj-y += memscrub.o

obj-y += grspw2.o

obj-$(CONFIG_KERNEL_PRINTK) += printk.o
obj-$(CONFIG_SYSCTL) += sysctl.o
obj-$(CONFIG_NOC_DMA) += noc_dma.o
obj-$(CONFIG_XENTIUM) += xentium.o
obj-$(CONFIG_TESTMODULE) += testmodule.o
