
CHECKFLAGS     += -D__sparc__


obj-y += setup.o
obj-y += init.o
obj-y += page.o
obj-y += bootmem.o
obj-y += mm.o
obj-y += elf.o
obj-y += module.o
obj-y += traps.o
obj-y += stacktrace.o
obj-y += stack.o
obj-y += traps/data_access_exception_trap.o
obj-y += traps/data_access_exception.o

#libs-y                 += lib/
