# Makefile for samples code

obj-$(CONFIG_SAMPLE_SYSCTL)	+= sysctl/
obj-$(CONFIG_SAMPLE_MM)		+= mm/
obj-$(CONFIG_SAMPLE_CHUNK)	+= chunk/
obj-$(CONFIG_SAMPLE_PROC_CHAIN)	+= proc_chain/
obj-$(CONFIG_SAMPLE_NOC_DMA)	+= noc_dma/
