
CHECKFLAGS     += -D__sparc__

lib-y += gptimer.o
lib-y += grtimer.o
lib-y += grtimer_longcount.o

lib-$(CONFIG_ARCH_CUSTOM_BOOT_CODE) += clz_tab.o
lib-$(CONFIG_ARCH_CUSTOM_BOOT_CODE) += divdi3.o
lib-$(CONFIG_ARCH_CUSTOM_BOOT_CODE) += moddi3.o
lib-$(CONFIG_ARCH_CUSTOM_BOOT_CODE) += udivdi3.o
lib-$(CONFIG_ARCH_CUSTOM_BOOT_CODE) += umoddi3.o
