
CHECKFLAGS     += -D__sparc__

lib-y += gptimer.o
lib-y += grtimer.o
lib-y += grtimer_longcount.o
lib-y += leon3_dsu.o
lib-y += leon3_memcfg.o
lib-y += ahb.o

lib-$(CONFIG_ARCH_CUSTOM_BOOT_CODE) += clz_tab.o
lib-$(CONFIG_ARCH_CUSTOM_BOOT_CODE) += divdi3.o
lib-$(CONFIG_ARCH_CUSTOM_BOOT_CODE) += moddi3.o
lib-$(CONFIG_ARCH_CUSTOM_BOOT_CODE) += udivdi3.o
lib-$(CONFIG_ARCH_CUSTOM_BOOT_CODE) += umoddi3.o
lib-$(CONFIG_ARCH_CUSTOM_BOOT_CODE) += floatdidf.o
